### ISSUE TITLE
Another crash

### ISSUE THREAD

**Issue by Matthysse** [exaskye/NotEnoughCreativity#9] opened 2021-01-24 12:28 UTC
Hello! with the new version you released that should repair the compatibility between Not enough Creativity and fast workbench, when clicking on the switch button I have this crash: https://pastebin.com/7CZwmW6D

**Comment by exaskye** [comment] 2021-01-28 18:32
I need a debug log for additional context. `.minecraft/logs/debug.log`

**Comment by Nousy-man** [comment] 2021-01-28 18:56
[2021-01-28-6.log.gz](https://github.com/unascribed/NotEnoughCreativity/files/5889462/2021-01-28-6.log.gz)

**Comment by Nousy-man** [comment] 2021-01-28 18:56
this?

**Comment by exaskye** [comment] 2021-01-28 19:13
No, debug.log. It contains detailed information about mixins.

**Comment by Nousy-man** [comment] 2021-01-28 20:04
[debug.log](https://github.com/unascribed/NotEnoughCreativity/files/5889735/debug.log)

**Comment by exaskye** [comment] 2021-01-28 20:28
...That is not a Minecraft log.

**Comment by Nousy-man** [comment] 2021-01-28 20:33
i am using curse forge
where do i find it?

**Comment by exaskye** [comment] 2021-01-28 22:08
It's in the Minecraft folder under "logs". You can access the "resourcepacks" folder under the Minecraft folder by going to Options > Resource Packs > Open Pack Folder.

**Comment by Nousy-man** [comment] 2021-01-29 08:30
the only log i find there is this

[latest.log](https://github.com/unascribed/NotEnoughCreativity/files/5892616/latest.log)

**Comment by exaskye** [comment] 2021-02-07 23:01
Turns out this is the same issue as #13, which has more discussion, so. Duplicate of #13

**Closed as completed by exaskye** 2021-02-07 23:01 UTC
Labels: k: Incompatibility, v: Forge 1.16
